// Generates everything in abi/ that isn't a versioned ABI JSON:
//   abi/<slug>/v<x>/index.ts  — one `export const <Contract>ABI = [...] as const;`
//                               per JSON in that version folder.
//   abi/<slug>/*.json         — copies of the latest version folder's JSONs
//                               (copies, not symlinks: raw GitHub URLs, Windows
//                               and some bundlers don't follow links).
//   abi/<slug>/index.ts       — `export * from "./<latest>/index.ts";`
//   abi/index.ts              — `export * as <ns> from "./<slug>/index.ts";` per component.
//
// `as const` is what viem needs for its ABI type inference to bite; inlining
// the JSON in the generated .ts (rather than importing it) preserves the
// literal types tsc otherwise widens away.
//
// `--check` writes nothing and exits 1 when any generated file is stale.

import { resolve } from "@std/path";
import { isVersionDir, latestVersion } from "./lib/abi.ts";

const GENERATED_BANNER = [
  "// Auto-generated by scripts/generate-abi-ts.ts.",
  "// Do not edit manually.",
  "",
];

// kebab-case slug → camelCase namespace name (`lock-to-vote` → `lockToVote`).
// Used only for the top-level `export * as <ns>` re-exports; the folder name
// stays as-is on disk.
function toCamel(slug: string): string {
  return slug.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
}

// Desired state of every generated file (path → content), plus the root JSONs
// that exist on disk but no longer belong (contract absent from the latest version).
export type Plan = { files: Map<string, string>; stale: string[] };

export async function planAbiTs(abiDir: string): Promise<Plan> {
  const files = new Map<string, string>();
  const stale: string[] = [];
  const slugs = (await listDirs(abiDir)).sort();

  for (const slug of slugs) {
    const slugDir = resolve(abiDir, slug);
    const versions = (await listDirs(slugDir)).filter(isVersionDir);
    const latest = latestVersion(versions);
    if (!latest) throw new Error(`abi/${slug} has no version folder (v<x.y>); run \`just import-abi ${slug}\``);

    for (const version of versions) {
      const contracts = await readJsons(resolve(slugDir, version));
      if (!contracts.size) throw new Error(`abi/${slug}/${version} has no ABI JSON`);
      const out = [...GENERATED_BANNER];
      for (const [name, raw] of contracts) {
        out.push(`export const ${name}ABI = ${JSON.stringify(JSON.parse(raw))} as const;`);
      }
      files.set(resolve(slugDir, version, "index.ts"), out.join("\n") + "\n");
      if (version !== latest) continue;
      for (const [name, raw] of contracts) files.set(resolve(slugDir, `${name}.json`), raw);
    }

    files.set(
      resolve(slugDir, "index.ts"),
      [...GENERATED_BANNER, `export * from "./${latest}/index.ts";`].join("\n") + "\n",
    );
    for (const name of (await readJsons(slugDir)).keys()) {
      const path = resolve(slugDir, `${name}.json`);
      if (!files.has(path)) stale.push(path);
    }
  }

  const rootOut = [...GENERATED_BANNER];
  for (const slug of slugs) rootOut.push(`export * as ${toCamel(slug)} from "./${slug}/index.ts";`);
  files.set(resolve(abiDir, "index.ts"), rootOut.join("\n") + "\n");
  return { files, stale };
}

// Returns the paths that differ from the plan (written unless `check`).
export async function generateAbiTs(abiDir: string, { check = false } = {}): Promise<string[]> {
  const { files, stale } = await planAbiTs(abiDir);
  const changed: string[] = [...stale];
  for (const [path, content] of files) {
    const current = await Deno.readTextFile(path).catch(() => undefined);
    if (current !== content) changed.push(path);
  }
  if (!check) {
    for (const path of stale) await Deno.remove(path);
    for (const path of changed) if (files.has(path)) await Deno.writeTextFile(path, files.get(path)!);
  }
  return changed;
}

async function listDirs(dir: string): Promise<string[]> {
  const out: string[] = [];
  for await (const e of Deno.readDir(dir)) if (e.isDirectory) out.push(e.name);
  return out;
}

// name → raw file content, sorted by name. Raw so root copies are byte-identical.
async function readJsons(dir: string): Promise<Map<string, string>> {
  const names: string[] = [];
  for await (const e of Deno.readDir(dir)) {
    if (e.isFile && e.name.endsWith(".json")) names.push(e.name.slice(0, -5));
  }
  names.sort((a, b) => a.localeCompare(b));
  const out = new Map<string, string>();
  for (const n of names) out.set(n, await Deno.readTextFile(resolve(dir, `${n}.json`)));
  return out;
}

if (import.meta.main) {
  const check = Deno.args.includes("--check");
  const abiDir = resolve(import.meta.dirname!, "..", "abi");
  const changed = await generateAbiTs(abiDir, { check });
  const rel = (p: string) => p.slice(abiDir.length - 3);
  if (check) {
    if (changed.length) {
      console.error(`abi/ is out of date (run \`just generate-abi\`):\n${changed.map((p) => `  ${rel(p)}`).join("\n")}`);
      Deno.exit(1);
    }
    console.error("abi/ generated files are up to date");
  } else {
    console.error(changed.length ? changed.map((p) => `  ✓ ${rel(p)}`).join("\n") : "  · nothing to regenerate");
  }
}
