// Walks abi/<component>/*.json and generates viem-compatible TypeScript
// bindings alongside them:
//   abi/<component>/index.ts   — one `export const <Contract>ABI = [...] as const;`
//                                 per JSON in the folder.
//   abi/index.ts               — `export * as <slug> from "./<slug>";` per component.
//
// `as const` is what viem needs for its ABI type inference to bite; inlining
// the JSON in the generated .ts (rather than importing it) preserves the
// literal types tsc otherwise widens away.

import { resolve } from "@std/path";

const HERE = import.meta.dirname!;
const ABI_DIR = resolve(HERE, "..", "abi");
const GENERATED_BANNER = [
  "// Auto-generated by scripts/generate-abi-ts.ts.",
  "// Do not edit manually.",
  "",
];

// kebab-case slug → camelCase namespace name (`lock-to-vote` → `lockToVote`).
// Used only for the top-level `export * as <ns>` re-exports; the folder name
// stays as-is on disk.
function toCamel(slug: string): string {
  return slug.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
}

export async function generateAbiTs(): Promise<void> {
  const componentSlugs: string[] = [];
  for await (const entry of Deno.readDir(ABI_DIR)) {
    if (entry.isDirectory) componentSlugs.push(entry.name);
  }
  componentSlugs.sort();

  let total = 0;
  for (const slug of componentSlugs) {
    const dir = resolve(ABI_DIR, slug);
    const contracts: Array<{ name: string; abi: unknown }> = [];
    for await (const entry of Deno.readDir(dir)) {
      if (!entry.isFile || !entry.name.endsWith(".json")) continue;
      const name = entry.name.replace(/\.json$/, "");
      const abi = JSON.parse(await Deno.readTextFile(resolve(dir, entry.name)));
      contracts.push({ name, abi });
    }
    contracts.sort((a, b) => a.name.localeCompare(b.name));

    const out = [...GENERATED_BANNER];
    for (const { name, abi } of contracts) {
      out.push(`export const ${name}ABI = ${JSON.stringify(abi)} as const;`);
    }
    await Deno.writeTextFile(resolve(dir, "index.ts"), out.join("\n") + "\n");
    console.error(`  ${slug}: ${contracts.length} contracts → ${slug}/index.ts`);
    total += contracts.length;
  }

  // Top-level re-exports: `import { admin, tokenVoting } from "./abi"`.
  const rootOut = [...GENERATED_BANNER];
  for (const slug of componentSlugs) {
    rootOut.push(`export * as ${toCamel(slug)} from "./${slug}/index.ts";`);
  }
  await Deno.writeTextFile(resolve(ABI_DIR, "index.ts"), rootOut.join("\n") + "\n");
  console.error(`\ntotal: ${total} ABIs across ${componentSlugs.length} components`);
}

if (import.meta.main) {
  await generateAbiTs();
}
